#!/bin/bash


########################################################
# Setup environment 
########################################################
IOTKITDIR=`pwd`;
export IOTKITDIR
sudo mkdir $IOTKITDIR/../iot-gateway-kit-depend
export IOTKITDEPEND=$IOTKITDIR/../iot-gateway-kit-depend


########################################################
# Read in the supporting functions 
########################################################
. $IOTKITDIR/scripts/funcs

########################################################
# Create install.log file
########################################################
sudo bash -c "echo 'Begin Install' > install.log"

########################################################
# Run apt-get update 
########################################################
LOGSTART "Run apt-get update"
. $IOTKITDIR/scripts/install.apt-get.update
LOGSTOP


########################################################
# Create Informix user
########################################################
LOGSTART "Create Informix User"
. $IOTKITDIR/scripts/install.informix.user
LOGSTOP




########################################################
# Install Node
########################################################
LOGSTART "Install Node"
. $IOTKITDIR/scripts/install.node
LOGSTOP


########################################################
# Install Node-red
########################################################
LOGSTART "Install Node-Red"
. $IOTKITDIR/scripts/install.nodered
LOGSTOP


########################################################
# Install Ble
########################################################
LOGSTART "Install Ble"
. $IOTKITDIR/scripts/install.ble
LOGSTOP


########################################################
# Install Zwave
########################################################
LOGSTART "Install Zwave"
#. $IOTKITDIR/scripts/install.zwave
LOGSTOP


########################################################
# Install Informix Product 
########################################################
LOGSTART "Install Informix Product"
. $IOTKITDIR/scripts/install.informix.prod
LOGSTOP


########################################################
# Install Informix General
########################################################
LOGSTART "Install Informix General"
. $IOTKITDIR/scripts/install.informix.general
LOGSTOP


########################################################
# Starting iot service 
########################################################
LOGSTART "Starting iot Service"
sudo service iot start
LOGSTOP



