#!/bin/bash

########################################################
# Setup environment 
########################################################
sudo mkdir $IOTKITDIR/../../iot-gateway-kit-depend 

########################################################
# Read in the supporting functions 
########################################################
. $IOTKITDIR/scripts/funcs

########################################################
# Create install.log file
########################################################
sudo bash -c "echo 'Begin Install' > install.log" 

########################################################
# Run apt-get update 
########################################################
LOGSTART "Run apt-get update"
. $IOTKITDIR/scripts/install.apt-get.update > $IOTKITDIR/LOG/update.log 2>&1
LOGSTOP


########################################################
# Create Informix user
########################################################
LOGSTART "Create Informix User"
. $IOTKITDIR/scripts/install.informix.user > $IOTKITDIR/LOG/user.log 2>&1
LOGSTOP




########################################################
# Install Node
########################################################
LOGSTART "Install Node"
. $IOTKITDIR/scripts/install.node > $IOTKITDIR/LOG/node.log 2>&1
LOGSTOP


########################################################
# Install Node-red
########################################################
LOGSTART "Install Node-Red"
. $IOTKITDIR/scripts/install.nodered > $IOTKITDIR/LOG/nodered.log 2>&1
LOGSTOP


########################################################
# Install Ble
########################################################
LOGSTART "Install Ble"
. $IOTKITDIR/scripts/install.ble > $IOTKITDIR/LOG/ble.log 2>&1
LOGSTOP


########################################################
# Install Zwave
########################################################
LOGSTART "Install Zwave"
#. $IOTKITDIR/scripts/install.zwave > $IOTKITDIR/LOG/zwave.log 2>&1 
LOGSTOP


########################################################
# Install Informix Product 
########################################################
LOGSTART "Install Informix Product"
. $IOTKITDIR/scripts/install.informix.prod > $IOTKITDIR/LOG/prod.log 2>&1
LOGSTOP


########################################################
# Install Informix General
########################################################
LOGSTART "Install Informix General"
. $IOTKITDIR/scripts/install.informix.general > $IOTKITDIR/LOG/informix.log 2>&1 
LOGSTOP

########################################################
# Starting iot service 
########################################################
LOGSTART "Starting iot Service"
sudo service informix stop  
sudo service iot start 
LOGSTOP



